<a href="https://colab.research.google.com/github/rushimhaisane8830/DS/blob/main/fetch_california_housing_DecisionTreeRegression.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [3]:
import pandas as pd
import numpy as np
from sklearn.datasets import fetch_california_housing

In [7]:
x, y = fetch_california_housing(return_X_y=True)

In [23]:
x[0]

array([   8.3252    ,   41.        ,    6.98412698,    1.02380952,
        322.        ,    2.55555556,   37.88      , -122.23      ])

In [22]:
y[0]

np.float64(4.526)

In [11]:
from sklearn.model_selection import train_test_split

In [12]:
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size=0.2, random_state=42)

In [13]:
from sklearn.tree import DecisionTreeRegressor

In [46]:
dtl = DecisionTreeRegressor(min_samples_split=8)

In [47]:
dtl.fit(x_train, y_train)

DecisionTreeRegressor(min_samples_split=5)

In [48]:
y_pred = dtl.predict(x_test)

In [49]:
from sklearn.metrics import r2_score

In [50]:
r2_score(y_test, y_pred)

0.6337735537082083

In [51]:
from sklearn.metrics import mean_squared_error

In [52]:
mean_squared_error(y_test, y_pred)

0.47990642329002253

In [53]:
from sklearn.metrics import mean_absolute_error

In [54]:
mean_absolute_error(y_test, y_pred)

0.4470266046915375

In [55]:
y_pred

array([0.4155 , 1.203  , 5.00001, ..., 5.00001, 0.65075, 2.1215 ])

In [56]:
val = [[   8.3252    ,   41.        ,    6.98412698,    1.02380952,
        322.        ,    2.55555556,   37.88      , -122.23      ]]

In [57]:
pred = dtl.predict(val)

In [58]:
pred

array([4.2145])